### ISSUE TITLE
Add scala.js version

### ISSUE THREAD

**Issue by ghost** [non/imp#1]
This very small library has all the hallmarks of one that will be used by many, many libraries. So please can we have a Scala.js version sooner rather than later, please?

**Comment by non** [comment]
Yes! I'll try to copy your examples from other projects -- it should be quite easy to support.

**Comment by ngbinh** [comment]
yeah, looks super useful.

**Comment by non** [comment]
As expected, the scala.js plugin seems to _just work_ here. Assuming I can get publishing right, a scala.js-enabled version should be coming momentarily.

**Comment by non** [comment]
I spoke too soon -- I failed to create a successful cross project. Still working on this.

**Comment by non** [comment]
Well -- it seems like maybe my use of `unmanagedSourceDirectories` is confounding the plugin.

I'll look at this more later tonight or tomorrow.

**Comment by non** [comment]
OK -- just released 0.2.0 to Sonatype, which supports scala.js 0.6.x.

I'll update the README once things have synced to Maven central. Whew! This was a bit more work than I expected.

**Comment by ngbinh** [comment]
:+1:
