### ISSUE TITLE
Publish 2.1 artifacts for Scala 2.10

### ISSUE THREAD

**Issue by nrinaudo** [non/imp#10]
This looks like an oversight, since:
- previous versions have [artifacts published](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.spire-math%22%20AND%20a%3A%22imp_2.10%22) for 2.10
- cross building appears to be [set up](https://github.com/non/imp/blob/master/build.sbt#L6)

**Comment by non** [comment]
Just released 0.3.0 which supports 2.10, 2.11, and 2.12.
